### PR TITLE
V2

### PR DESCRIPTION
**Pull request by georgyangelov**
A PR just to have an easier reference to the `v2` branch. Everyone is welcome to push here.

### CODE REVIEW

**Comment by Dancanplay** [comment]
Are we planning to deploy the extension on other browsers? I just loaded it up on Firefox and Edge without problem.

**Comment by georgyangelov** [comment]
This is interesting. I haven't made any extensions for Firefox/Edge but I assumed it has a different format (manifest.json) and APIs (messages between background pages, etc.). Do they use the same things?

**Comment by Dancanplay** [comment]
Yeah, Firefox and Edge are supporting the universal WebExtensions. I got the extension running in Firefox just loading it with manifest.json, and Edge is using almost the same thing.
image
image

**Comment by georgyangelov** [comment]
This is really neat! So there aren't any changes required to the manifest? We can publish the extension for Firefox and Edge as well once we are ready with V2.

P.S. Is there an Edge Store? :)

**Comment by Dancanplay** [comment]
Firefox handles the manifest straight without changes. However, Edge has some differences in manifest and needs to be validated through Extension toolkit.
Edge uses Windows 10 store for extensions. Publishing to store is not open to public at the moment.

**Comment by georgyangelov** [comment]
@Dancanplay, @NSDex, Can you please review and test this branch? I think we are ready to merge it, I made it support both the old and the new YouTube design. I moved the current `dark.css` to `statics/legacy_styles.css`.

I see no problem making this the current master and releasing with these changes. The styles for the new design are incomplete but they are a good start.

**Review by deancanen — APPROVED** [review]
Seems to be working fine on my side.

**Pull request merged**
