### PR TITLE
Include more AlienTube changes

### PR DESCRIPTION
**Pull request by link07**
Changes more of AlienTube to a dark theme, and fixes some issues with the tab bar

### CODE REVIEW

**Comment by stormbreakerbg** [comment]
Thank you for the changes :) Can you squash the commits and remove the `-o` `-ms` `-moz` prefixes and the IE `filter`? It's a chrome extension, these aren't necessary. :smile:

**Comment by link07** [comment]
Oh duh, that's what I get for copying css around haha, I'll do that now

**Comment by link07** [comment]
and I squashed it :)

**Comment by stormbreakerbg** [comment]
Thanks :) Will release it tomorrow. :)

**Pull request merged**
